@startuml

package "U I" {
  class Kakeibo
  {

  }

  class SpecifyCardStatement
  {

  }
}

package DataProcess {
  interface IStatement{
    +GetSheet() : DataSet
    +GetCompany() : CardCompanies
  }

  class Statement{
    +ctor(CardCompanies company, string path)
  }

  interface IEdit{
    +Editable() : bool
    +Edit() : CardCompanies
  }
}

package DataBase {
  class DataSet{}

  class StatementDataSet{
    
  }
}


IStatement <|-- Statement
IEdit <|-- Statement

SpecifyCardStatement --> IStatement
Kakeibo --> IEdit


DataSet <|-- StatementDataSet

@enduml